image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - test
  - package
  - deploy

maven-test:
  image: maven:3-jdk-11
  stage: build
  script: "mvn test"
  artifacts:
    paths:
      - target/*.jar

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
    - docker build -t marmiss/search-service:${CI_COMMIT_TAG}
    - docker push marmiss/search-service:${CI_COMMIT_TAG}
Deploy to Dev:
  only:
    - tags
    - staging
  stage: deploy
  script: docker push marmiss/booking-service:${CI_COMMIT_TAG}