image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - test
  - build
  - deploy

maven-test:
  image: maven:3-jdk-11
  stage: test
  script: "mvn test"


maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn clean install"


docker-build:
  only:
    - tags
    - staging
  stage: deploy
  script:
    - docker build -t marmiss/booking-service:${CI_COMMIT_TAG}
    - docker push marmiss/booking-service:${CI_COMMIT_TAG}
