amadeusBaseUrl: http://test.api.amadeus.com
amadeusAuthenticationUrl: https://test.api.amadeus.com:443/v1/security/oauth2/token
amadeusApiKey: ${AMADEUS_API_KEY:Sy6SmGaxkTPgN6e1omulC6pIJroa2r7v}
amadeusApiSecret: ${AMADEUS_API_SECRET:I4EgLbzbjqAVU1Pb}
searchServiceBaseUrl: http://search.xeelver.svc.cluster.local

server:
  port: 80

logging:
  level:
    root: INFO
    org.springframework.web: INFO
spring:
  mvc:
    converters:
      preferred-json-mapper: gson